# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SwiftUIChat' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SwiftUIChat
pod 'Firebase'
 pod 'Firebase/Database'
 pod 'Firebase/Analytics'
 pod 'Firebase/Core'
 pod 'Firebase/DynamicLinks'
 pod 'Firebase/Messaging'
 pod 'Firebase/Auth','6.16.0'

post_install do |installer_representation|
     installer_representation.pods_project.targets.each do |target|
         target.build_configurations.each do |config|
             config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
             config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
             config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
        end
     end
  end
  

end
